# Generated by Django 4.2.11 on 2024-04-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200, verbose_name='Vprašanje')),
                ('question_type', models.CharField(choices=[('textbox', 'textbox'), ('multipleselect', 'multipleselect'), ('radiobutton', 'radiobutton'), ('numvalue', 'numvalue'), ('boolean', 'boolean')], default='textbox', help_text='Izberi tip vprašanja', max_length=20, verbose_name='Tip')),
                ('max_choices', models.IntegerField(blank=True, null=True, verbose_name='Max odgovorov')),
                ('question_values', models.CharField(blank=True, max_length=500, null=True, verbose_name='Vrednosti')),
                ('question_grade', models.IntegerField(default=1, verbose_name='Točke')),
                ('question_grade_partials', models.CharField(blank=True, max_length=200, null=True, verbose_name='Multi: Delne točke,Bool: False value')),
                ('question_grade_range', models.IntegerField(blank=True, default=1, null=True, verbose_name='Rang +-')),
                ('question_grade_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Opis ocene')),
            ],
            options={
                'verbose_name': 'Vprašanje',
                'verbose_name_plural': 'Vprašanja',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season_name', models.CharField(default='', max_length=200, verbose_name='Ime Sezone')),
            ],
            options={
                'verbose_name': 'Sezona',
                'verbose_name_plural': 'Sezone',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poll_name', models.CharField(max_length=200, verbose_name='Ime kviza')),
                ('question_ids', models.CharField(max_length=200, verbose_name='Serija vprašanj')),
                ('is_active', models.BooleanField(default=False, help_text='Samo en aktiven kviz na enkrat', verbose_name='Aktiven')),
                ('is_grading', models.BooleanField(default=False, help_text='Samo en aktiven kviz na enkrat', verbose_name='Ocenjevanje')),
                ('is_results', models.BooleanField(default=False, help_text='Ali se rezultati pokažejo na www', verbose_name='Rezultati')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.season')),
            ],
            options={
                'verbose_name': 'Kviz',
                'verbose_name_plural': 'Kvizi',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userEmail', models.CharField(default='', max_length=200, verbose_name='Email')),
                ('userName', models.CharField(default='', max_length=200, verbose_name='Ime')),
                ('userGroup', models.CharField(default='', max_length=200, verbose_name='Skupina')),
                ('value', models.CharField(max_length=200, verbose_name='Odgovor')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Točke')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
            options={
                'verbose_name': 'Odgovor',
                'verbose_name_plural': 'Odgovori',
            },
        ),
    ]
