# Generated by Django 4.2.11 on 2024-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_grade_range',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rang +-'),
        ),
    ]
