# Generated by Django 5.1.1 on 2025-04-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_question_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_finale',
            field=models.BooleanField(default=False, help_text='Ali se rezultati pokažejo na www (samo finale)', verbose_name='Finale'),
        ),
    ]
